# Uncomment the next line to define a global platform for your project
  platform :ios, '12.0'

target 'Films' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Films
  pod 'Moya', '~> 15.0'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'AlamofireImage', '~> 4.1'
  pod 'SwiftLint'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
end
